import { createClient } from '@/lib/supabase/server'
import { notFound } from 'next/navigation'

// Shot type → short label for reel name (max 8 chars, EDL standard)
const SHOT_ABBREV: Record<string, string> = {
  establishing:       'EST',
  wide:               'WD',
  medium_wide:        'MW',
  medium:             'MED',
  medium_close:       'MC',
  close_up:           'CU',
  extreme_close_up:   'ECU',
  over_the_shoulder:  'OTS',
  pov:                'POV',
  insert:             'INS',
  cutaway:            'CUT',
}

function frames(seconds: number, fps: number) {
  return Math.round(seconds * fps)
}

function toTC(totalFrames: number, fps: number) {
  const s = Math.floor(totalFrames / fps)
  const f = totalFrames % fps
  const m = Math.floor(s / 60)
  const h = Math.floor(m / 60)
  return [
    String(h).padStart(2, '0'),
    String(m % 60).padStart(2, '0'),
    String(s % 60).padStart(2, '0'),
    String(f).padStart(2, '0'),
  ].join(':')
}

// Sanitise a string for EDL comment lines (no newlines)
function edlStr(str: string | null | undefined, maxLen = 100) {
  if (!str) return ''
  return str.replace(/[\r\n]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, maxLen)
}

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  const url = new URL(request.url)
  const fps = parseInt(url.searchParams.get('fps') ?? '25')
  const ntsc = fps === 29 || fps === 30 // use drop-frame for NTSC rates

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return new Response('Unauthorized', { status: 401 })

  const [{ data: episode }, { data: shots }] = await Promise.all([
    supabase
      .from('episodes')
      .select('*, seasons(title, format, brands(company_name), creators(name))')
      .eq('id', id)
      .single(),
    supabase
      .from('shots')
      .select('*')
      .eq('episode_id', id)
      .order('number', { ascending: true }),
  ])

  if (!episode) return notFound()
  if (!shots || shots.length === 0) {
    return new Response('No shots found for this episode', { status: 400 })
  }

  const season = episode.seasons as any
  const title = `${season?.title ?? 'Season'} — Ep ${episode.number}${episode.title ? ` — ${episode.title}` : ''}`

  // Build EDL lines
  let recordCursor = 0
  const lines: string[] = []

  for (const shot of shots as any[]) {
    const num = String(shot.number).padStart(3, '0')
    const durationSec = shot.duration_seconds ?? 4
    const durationF = frames(durationSec, fps)

    // Reel name: shot type abbrev + number, e.g. "CU-001" (max 8 chars)
    const abbrev = SHOT_ABBREV[shot.shot_type ?? ''] ?? 'SH'
    const reel = `${abbrev}-${num}`.slice(0, 8)

    // Source: each clip runs 00:00:00:00 → clip duration from head of "reel"
    const srcIn  = toTC(0, fps)
    const srcOut = toTC(durationF, fps)

    // Record: where it sits on the timeline
    const recIn  = toTC(recordCursor, fps)
    const recOut = toTC(recordCursor + durationF, fps)
    recordCursor += durationF

    // CMX 3600 edit line
    lines.push(`${num}  ${reel.padEnd(8)}  V  C  ${srcIn} ${srcOut} ${recIn} ${recOut}`)

    // FROM CLIP NAME — DaVinci picks this up as the clip's display name
    const clipName = `${num} — ${edlStr(shot.description ?? shot.scene_beat ?? 'Shot', 80)}`
    lines.push(`* FROM CLIP NAME: ${clipName}`)

    // Camera / shot details
    const shotLabel = [
      shot.shot_type?.replace(/_/g, ' '),
      shot.camera_angle?.replace(/_/g, ' '),
      shot.camera_movement?.replace(/_/g, ' '),
    ].filter(Boolean).join(' | ')
    if (shotLabel) lines.push(`* SHOT: ${shotLabel}`)

    // Scene beat
    if (shot.scene_beat) lines.push(`* BEAT: ${edlStr(shot.scene_beat)}`)

    // Dialogue
    if (shot.dialogue) lines.push(`* DIALOGUE: ${edlStr(shot.dialogue)}`)

    // Props
    if (shot.props) lines.push(`* PROPS: ${edlStr(shot.props)}`)

    // Director notes
    if (shot.notes) lines.push(`* NOTES: ${edlStr(shot.notes)}`)

    // Duration note
    lines.push(`* DURATION: ${durationSec}s`)

    lines.push('') // blank line between edits
  }

  const totalSec = shots.reduce((acc: number, s: any) => acc + (s.duration_seconds ?? 0), 0)

  const edl = [
    `TITLE: ${edlStr(title, 100)}`,
    `FCM: ${ntsc ? 'DROP FRAME' : 'NON-DROP FRAME'}`,
    '',
    ...lines,
    `* SEQUENCE INFO: ${shots.length} shots · ${totalSec}s total · ${fps}fps · Generated by TCF Studios`,
  ].join('\n')

  const safeName = (season?.title ?? 'Season').replace(/[^a-zA-Z0-9]/g, '_')
  const filename = `TCF_${safeName}_Ep${episode.number}_${fps}fps.edl`

  return new Response(edl, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  })
}
